---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  labels:
    app: postgre
  namespace: blockscout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14
          imagePullPolicy: IfNotPresent
          # 공유 버퍼의 크기는 기본 32M 이지만, 서버 메모리 기준으로 1/4 ~ 1/2 정도로 할당
          args: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
          resources:
            requests:
              cpu: 1024m
              memory: 1024Mi
            limits:
              cpu: 1024m
              memory: 1024Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: PGDATA # 데이터베이스 파일을 다른 위치에 저장되도록 함??
            #   value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB # 생성할 데이터베이스 (정의하지 않는다면 POSTGRES_USER로 생성)
              value: blockscout
            # - name: POSTGRES_HOST_AUTH_METHOD # 보안상 사용하지 말것
            #   value: "trust"
            - name: POSTGRES_PASSWORD
              value: "postgre"
            - name: POSTGRES_USER
              value: "postgre"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
      volumes:
        - name: db-data
          emptyDir:
            sizeLimit: "30Gi"
