apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: explorer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30040
      protocol: TCP
      name: explorer
