apiVersion: v1
kind: Service
metadata:
  name: besu-member1-1
  labels:
    app: member1
  namespace: besu
spec:
  type: NodePort
  selector:
    app: member1
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30045
      protocol: TCP
      name: member1