apiVersion: v1
kind: Service
metadata:
  name: quorum-validator1-1
  labels:
    app: validator1
  namespace: quorum
spec:
  type: NodePort
  selector:
    app: validator1
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30045
      protocol: TCP
      name: validator1rpc