apiVersion: v1
kind: Service
metadata:
  name: besu-validator4-1
  labels:
    app: validator4
  namespace: besu
spec:
  type: NodePort
  selector:
    app: validator4
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30085
      protocol: TCP
      name: validator4
