apiVersion: v1
kind: Service
metadata:
  name: besu-validator1-1
  labels:
    app: validator1
  namespace: besu
spec:
  type: NodePort
  selector:
    app: validator1
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30055
      protocol: TCP
      name: validator1
