apiVersion: v1
kind: Service
metadata:
  name: besu-validator2-1
  labels:
    app: validator2
  namespace: besu
spec:
  type: NodePort
  selector:
    app: validator2
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30065
      protocol: TCP
      name: validator2
