apiVersion: v1
kind: Service
metadata:
  name: sig-provider
  labels:
    app: sig-provider
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: sig-provider
  ports:
    - port: 8151
      targetPort: 8050
      nodePort: 30151
      protocol: TCP
      name: blockscout
