apiVersion: v1
kind: Service
metadata:
  name: smart-contract-verifier
  labels:
    app: smart-contract-verifier
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: smart-contract-verifier
  ports:
    - port: 8150
      targetPort: 8050
      nodePort: 30150
      protocol: TCP
      name: blockscout
