apiVersion: v1
kind: Service
metadata:
  name: visualizer
  labels:
    app: visualizer
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: visualizer
  ports:
    - port: 8152
      targetPort: 8050
      nodePort: 30152
      protocol: TCP
      name: blockscout
