{
 "title": "ChainZ Besu Monitering",
 "description": "Provides an overview of Besu nodes",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": { "query": "ethereum_blockchain_height" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (ethereum_blockchain_height{})"
    },
    {
     "expr": "sum by (instance) (ethereum_best_known_block_number{} - ethereum_blockchain_height{})"
    },
    {
     "expr": "sum by (instance) (1/rate(ethereum_blockchain_height{}[60s]))"
    },
    {
     "expr": "sum by (instance) (besu_blockchain_chain_head_transaction_count{})"
    },
    {
     "expr": "sum by (instance) (besu_blockchain_chain_head_gas_used{})"
    },
    {
     "expr": "sum by (instance) (besu_blockchain_chain_head_gas_limit{})"
    },
    {
     "expr": "sum by (instance) (ethereum_peer_count{})"
    },
    {
     "expr": "sum by (instance) (time() - process_start_time_seconds{})"
    },
    {
     "expr": "sum by (instance) (besu_transaction_pool_transactions_added_total{})"
    }
   ]
  },
  {
   "title": "Blockchain CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "core" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{}[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockchain Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "ethereum_blockchain_height{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(ethereum_blockchain_height{}[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gas Uesd (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "100 * besu_blockchain_chain_head_gas_used{} / besu_blockchain_chain_head_gas_limit{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions in Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "besu_blockchain_chain_head_transaction_count{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "besu_transaction_pool_transactions{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Pool Added (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (increase(besu_transaction_pool_transactions_added_total{source!='pool'}[60s])) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}