
apiVersion: v1
kind: Service
metadata:
  name: blockscout-dev-mainnet
  labels:
    app: blockscout-dev-mainnet
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: blockscout-dev-mainnet
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31402
      protocol: TCP
      name: blockscout-dev-main
