
apiVersion: v1
kind: Service
metadata:
  name: blockscout2
  labels:
    app: blockscout2
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: blockscout2
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31401
      protocol: TCP
      name: blockscout2
