apiVersion: v1
kind: Service
metadata:
  name: sig-provider1
  labels:
    app: sig-provider1
  namespace: blockscout
spec:
  type: NodePort
  selector:
    app: sig-provider
  ports:
    - port: 8150
      targetPort: 8050
      nodePort: 30151
      protocol: TCP
      name: blockscout

---
apiVersion: v1
kind: Service
metadata:
  name: sig-provider
  labels:
    app: sig-provider
  namespace: blockscout
spec:
  type: ClusterIP
  selector:
    app: sig-provider
  ports:
    - port: 8050
      targetPort: 8050
      protocol: TCP
      name: http
