apiVersion: v1
kind: Secret
metadata:
  name: besu-validator1-key
  labels:
    app: besu-validator1-key
  namespace: besu
type: Opaque
stringData:
  nodekey: |-
    3073f2e00933ab2b52c33b5c114a20f0d38dbb569ee96cb80251d4cd4fb2824f