apiVersion: v1
kind: Secret
metadata:
  name: besu-validator3-key
  labels:
    app: besu-validator3-key
  namespace: besu
type: Opaque
stringData:
  nodekey: |-
    ca4ae1b139f22c666ab02c5a643c53b7f2055137b7405c8b18dc8b38ee8ca9fb
