apiVersion: v1
kind: Secret
metadata:
  name: besu-validator2-key
  labels:
    app: besu-validator2-key
  namespace: besu
type: Opaque
stringData:
  nodekey: |-
    fb40fb2cfc62a4a51fa8e6f9cba7c396f9db8e3b6782fbb46d5676630e2650e7
