apiVersion: v1
kind: Service
metadata:
  name: alethio
  labels:
    app: alethio
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: alethio
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31081
      protocol: TCP
      name: alethio
