apiVersion: v1
kind: ConfigMap
metadata:
  name: common-blockscout-env
  labels:
    app: common-blockscout-env
  namespace: blockscout
data:
  # item # : templete에 추가하지 않았음.(원래 없던 것 추가할지 생각해볼것)
  ## item ## : templete에 추가하지 않았음.(원래 있었지만 뺄것?)
  #V item #V : templete에 추가하지 않았음.(변수가 아니라 값으로 추가할것)
  ### General
  DATABASE_URL: postgresql://postgre:postgre@db-postgre.blockscout:5432/blockscout?ssl=false
  ETHEREUM_JSONRPC_VARIANT: besu
  ETHEREUM_JSONRPC_HTTP_URL: http://besu-validator1.besu:8545/
  ETHEREUM_JSONRPC_TRACE_URL: http://besu-validator1.besu:8545/
  ETHEREUM_JSONRPC_WS_URL: ws://besu-validator1.besu:8546/
  ETHEREUM_JSONRPC_TRANSPORT: http
  ETHEREUM_JSONRPC_HTTP_INSECURE: "true" # false??
  ETHEREUM_JSONRPC_HTTP_TIMEOUT: "60"
  NETWORK: Local
  SUBNETWORK: Chainz Testnet
  ## IPC_PATH: "" 
  NETWORK_PATH: / 
  BLOCKSCOUT_HOST: "" # localhost
  BLOCKSCOUT_PROTOCOL: "" # in prod env https is used, in dev env http is used
  #V SECRET_KEY_BASE: "" # how to??
  #CHECK_ORIGIN: "false"
  PORT: "4000"
  COIN: ETH # 이 항목의 코인은 CoinGecko API를 통해 확인되어 그래프 및 UI의 다른 영역에서 USD 가격을 얻습니다.
  #COIN_NAME: CHZ # 코인의 표시되는 이름
  COIN_NAME: coins # 코인의 표시되는 이름
  EMISSION_FORMAT: DEFAULT
  #CHAIN_SPEC_PATH: "" # x
  #SUPPLY_MODULE: ""
  POOL_SIZE: "30"  # 
  POOL_SIZE_API: "30" # 
  ECTO_USE_SSL: "false"
  HEART_BEAT_TIMEOUT: "60"
  #HEART_COMMAND: ""
  #ELIXIR_VERSION: ""
  #GRAPHIQL_TRANSACTION: ""
  DISABLE_WEBAPP: "false"
  DISABLE_READ_API: "false"
  DISABLE_WRITE_API: "true" # need read only ??
  #WEBAPP_URL: "" # what mean?
  #API_URL: ""    # what mean?
  WOBSERVER_ENABLED: "true" # metrics : need enable ?
  CHECKSUM_ADDRESS_HASHES: "true"
  CHECKSUM_FUNCTION: eth
  #RESTRICTED_LIST
  #RESTRICTED_LIST_KEY
  #CHAIN_ID: ""
  #JSON_RPC: ""
  #HEALTHY_BLOCKS_PERIOD: "5m"
  #NEW_TAGS:
  #CUSTOM_CONTRACT_ADDRESSES_${tag_name}: ""
  #API_V2_ENABLED: ""
  #V TOKEN_ID_MIGRATION_FIRST_BLOCK: "0"
  #V TOKEN_ID_MIGRATION_CONCURRENCY: "1"
  #V TOKEN_ID_MIGRATION_BATCH_SIZE: "500" 
  #SESSION_COOKIE_DOMAIN: ""
  #DECODE_NOT_A_CONTRACT_CALLS: "false"

  ### Indexer management
  BLOCK_TRANSFORMER: base
  DISABLE_INDEXER: "false"
  INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "false" # not need?
  INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "false"
  #INDEXER_DISABLE_BLOCK_REWARD_FETCHER: "false" # not need?
  #INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: "false"
  #INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER: "false" # not need?
  INDEXER_MEMORY_LIMIT: "1gb" # need higher
  #V INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE: "100" # Batch size for empty block sanitizer (re-fetcher).
  #V INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: "10" # Batch size for blocks catchup fetcher. 
  #V INDEXER_CATCHUP_BLOCKS_CONCURRENCY: "10" # Concurrency for blocks catchup fetcher.
  #INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER: "false"
  #
  #DISABLE_REALTIME_INDEXER: "false" 
  #FIRST_BLOCK: "0"
  #LAST_BLOCK: ""
  #TRACE_FIRST_BLOCK: "0"
  #TRACE_LAST_BLOCK: ""
  #BLOCK_RANGES: ??
  #FETCH_REWARDS_WAY: "trace_block"
  #ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT: "5s" # geth에서만 사용되는 듯
  #ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: "false"
  #ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE: "default"  # how to besu??
  #
  #DISABLE_TOKEN_INSTANCE_FETCHER: "false"
  #V INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE: "10"
  #V INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY: "4"
  #V INDEXER_BLOCK_REWARD_BATCH_SIZE: "10"
  #V INDEXER_BLOCK_REWARD_CONCURRENCY: "4"
  #V INDEXER_TOKEN_INSTANCE_BATCH_SIZE: "1"
  #V INDEXER_TOKEN_INSTANCE_CONCURRENCY: "10"
  #V INDEXER_RECEIPTS_BATCH_SIZE: "250"
  #V INDEXER_RECEIPTS_CONCURRENCY: "10"
  #V INDEXER_COIN_BALANCES_BATCH_SIZE: "500"
  #V INDEXER_COIN_BALANCES_CONCURRENCY: "4"
  #
  #V INDEXER_TX_ACTIONS_ENABLE: "false" # 무슨 기능일까??
  #INDEXER_TX_ACTIONS_MAX_TOKEN_CACHE_SIZE: "100000"
  #INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK: ""
  #INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK: ""
  #INDEXER_TX_ACTIONS_REINDEX_PROTOCOLS: ""
  #INDEXER_CATCHUP_MISSING_RANGES_BATCH_SIZE: "100000"
  #MIN_MISSING_BLOCK_NUMBER_BATCH_SIZE: "100000"
  #INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE: "call_tracer"

  ### Exchange rates management
  DISABLE_EXCHANGE_RATES: "true"
  # ...
  DISABLE_TOKEN_EXCHANGE_RATE: "true" # 필요한가??

  ### Cache management (최적화 필요할 듯)
  #CACHE_TXS_COUNT_PERIOD: "2h"
  # ...

  ### Gas price oracle management (price가 0이므로 리소스 최소화 방안은 ??)
  #V GAS_PRICE_ORACLE_NUM_OF_BLOCKS: "2" # default: 200
  #GAS_PRICE_ORACLE_SAFELOW_PERCENTILE: "35"
  #GAS_PRICE_ORACLE_AVERAGE_PERCENTILE: "60"
  #GAS_PRICE_ORACLE_FAST_PERCENTILE: "90"
  #V GAS_PRICE_ORACLE_CACHE_PERIOD: "1h" # default: 30s

  ### Main page dashboard management
  GAS_PRICE: "0" # ()
  ENABLE_TXS_STATS: "true"
  SHOW_PRICE_CHART: "false"
  SHOW_TXS_CHART: "true"
  HISTORY_FETCH_INTERVAL: "30m" # default 1h => 무엇에 대한 내용?
  #TXS_HISTORIAN_INIT_LAG: "0"
  #TXS_STATS_DAYS_TO_COMPILE_AT_INIT: "32" # 메인 페이지의 일별 txs 수 기록 차트에 표시하기 위해 일별 txs 수 기록을 가져오는 일수입니다.

  ### Header management
  LOGO: /images/blockscout_logo.svg
  SHOW_TESTNET_LABEL: "false"
  TESTNET_LABEL_TEXT: "Testnet"
  SUPPORTED_CHAINS: '[ {"title": "Dev Chainz", "url": "https://dev-block-explorer.chainz.biz/"}, {"title": "Dev Chainz", "url": "https://dev-test-block-explorer.chainz.biz/", "test_net?": true}, {"title": "Chainz", "url": "https://block-explorer.chainz.biz/"}, {"title": "Chainz", "url": "https://test-block-explorer.chainz.biz/", "test_net?": true}, {"title": "Ethereum", "url": "https://blockscout.com/eth/mainnet/", "other?": true} ]'
  #V APPS_MENU: "false" # need??
  #V APPS: ""

  ### Footer management
  LOGO_FOOTER: /images/blockscout_logo.svg
  BLOCKSCOUT_VERSION: "v5.1.2"
  RELEASE_LINK: "https://github.com/blockscout/blockscout/tree/v5.1.2-beta"
  #RELEASE_LINK: "https://github.com/blockscout/blockscout/tree/${BLOCKSCOUT_VERSION}-beta"
  #FOOTER_CHAT_LINK: "https://discord.gg/3CtNAqVMRV" # 바닥글의 채팅 메뉴 항목에 연결합니다.
  #V FOOTER_ENABLE_FORUM_LINK: "false"
  #V FOOTER_GITHUB_LINK: "true"
  #V LINK_TO_OTHER_EXPLORERS: "false"  # if true, use OTHER_EXPLORERS.
  #V OTHER_EXPLORERS: '{}'

  ### Contract management
  CONTRACT_VERIFICATION_ALLOWED_EVM_VERSIONS: "homestead, tangerineWhistle, spuriousDragon, byzantium, constantinople, petersburg, istanbul"
  #CONTRACT_VERIFICATION_MAX_LIBRARIES: "" # default 10
  CONTRACT_MAX_STRING_LENGTH_WITHOUT_TRIMMING: "2040"
  #CONTRACT_DISABLE_INTERACTION: "" # default false

  ### Misc UI management
  SHOW_ADDRESS_MARKETCAP_PERCENTAGE: "false" # 수정
  SHOW_MAINTENANCE_ALERT: "false"
  MAINTENANCE_ALERT_MESSAGE: ""  # 익스플로러 상단 공지사항의 메시지 텍스트입니다.
  HIDE_BLOCK_MINER: "false"  # 값이 'true'인 경우 블록 페이지 및 타일에서 광부/검증기/시퀀서를 숨깁니다.
  DISPLAY_TOKEN_ICONS: "false" # true인 경우 TrustWallet 자산 저장소의 토큰 아이콘을 표시합니다.
  UNCLES_IN_AVERAGE_BLOCK_TIME: "false" # 우리는 엉클블록이 없음
  COIN_BALANCE_HISTORY_DAYS: "10" # default 10 : token 창의 하단 메뉴 중 하나에 관련된 것인듯? -> DB 조회 조건
  ADMIN_PANEL_ENABLED: "false"  # 
  #DISABLE_ADD_TO_MM_BUTTON: "true" # (for test) true인 경우 "MM에 체인 추가" 버튼이 나타나지 않습니다.
  #PERMANENT_DARK_MODE_ENABLED: "false" 
  #PERMANENT_LIGHT_MODE_ENABLED: "false"

  ### API rate limit management
  ## API_RATE_LIMIT: "50" # 전역 API 속도 제한: 모든 사용자에 대한 초당 요청 수 또는 요청.
  ## API_RATE_LIMIT_BY_KEY: "50"
  ## API_RATE_LIMIT_BY_IP: "50"
  ## API_RATE_LIMIT_STATIC_API_KEY: ""
  ## API_RATE_LIMIT_WHITELISTED_IPS: ""
  #API_RATE_LIMIT_DISABLED: "false"

  ### Specific smart-contracts

  ### Account-related ENV variables
  #V ACCOUNT_ENABLED: "false"
  # ...
  
  ### Smart-contract verifier => 어떻게 무얼해야되는지 모르겠음
  ENABLE_RUST_VERIFICATION_SERVICE: "false"
  #RUST_VERIFICATION_SERVICE_URL: ""
  RUST_VERIFICATION_SERVICE_URL: "http://smart-contract-verifier.blockscout:8050"

  ### Sol2Uml => solidity code가 연결되어야 실행 버튼이 보이는 듯?
  VISUALIZE_SOL2UML_ENABLED: "false"
  #VISUALIZE_SOL2UML_SERVICE_URL: ""
  VISUALIZE_SOL2UML_SERVICE_URL: "http://visualizer.blockscout:8050"

  ### Sig-provider => 뭐하는 것인지 모르겠음
  SIG_PROVIDER_ENABLED: "false"
  #SIG_PROVIDER_SERVICE_URL: ""
  SIG_PROVIDER_SERVICE_URL: "http://sig-provider.blockscout:8050"

  ### Sourcify : need ?? => Gnosis 기준 => 사용할 경우, Code 버튼 클릭시 에러발생
  ENABLE_SOURCIFY_INTEGRATION: "false"
  SOURCIFY_REPO_URL: "https://repo.sourcify.dev/contracts/"
  SOURCIFY_SERVER_URL: "https://sourcify.dev/server"

  ### Tenderly => 필요없어보임
  # SHOW_TENDERLY_LINK: "false"
  # TENDERLY_CHAIN_PATH: ""

  ### Datadog
  ### Spandex
  ### Analytics

  ### Deprecated ENV Variables
  # ADDRESS_COUNT_CACHE_PERIOD: "7200"
  # ADDRESS_SUM_CACHE_PERIOD: "3600"
  # ADDRESS_TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD: "1800"
  # ADDRESS_TOKENS_USD_SUM_CACHE_PERIOD: "1800"
  # ADDRESS_TRANSACTIONS_CACHE_PERIOD: "1800"
  # ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_CACHE_PERIOD: "1800"
  # ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: "1800"
  # ALLOWED_EVM_VERSIONS: homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,default
  # API_PATH: /
  # AVERAGE_BLOCK_CACHE_PERIOD: "1800"
  # BLOCK_COUNT_CACHE_PERIOD: "7200"
  # BRIDGE_MARKET_CAP_UPDATE_INTERVAL: "1800"
  # CUSTOM_CONTRACT_ADDRESSES_TEST_TOKEN: ""
  # DISABLE_BRIDGE_MARKET_CAP_UPDATER: "true"
  # DISABLE_KNOWN_TOKENS: "false"
  # ENABLE_POS_STAKING_IN_MENU: "false"
  # EXTERNAL_APPS: '[]'
  # MARKET_HISTORY_CACHE_PERIOD: "21600"
  # MAX_SIZE_UNLESS_HIDE_ARRAY: "50"
  # RE_CAPTCHA_CLIENT_KEY: ""
  # RE_CAPTCHA_SECRET_KEY: ""
  # SHOW_STAKING_WARNING: "false"
  # SOCKET_ROOT: /
  # STAKING_WARNING_MESSAGE: ""
  # TOKEN_EXCHANGE_RATE_CACHE_PERIOD: "1800"
  # TOKEN_HOLDERS_COUNTER_CACHE_PERIOD: "3600"
  # TOKEN_METADATA_UPDATE_INTERVAL: "172800"
  # TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD: "3600"
  # TOTAL_GAS_USAGE_CACHE_PERIOD: "3600"
  # TXS_COUNT_CACHE_PERIOD: "7200"
  # TXS_HISTORIAN_INIT_LAG: "0"
  # TXS_STATS_DAYS_TO_COMPILE_AT_INIT: "10"
  
