
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: member1-sa
  namespace: besu

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: member1-key-read-role
  namespace: besu
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [ besu-member1-key ]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: member1-rb
  namespace: besu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: member1-key-read-role
subjects:
  - kind: ServiceAccount
    name: member1-sa
    namespace: besu

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: member1
  labels:
    app: member1
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member1
  serviceName: besu-member1
  template:
    metadata:
      labels:
        app: member1
    spec:
      serviceAccountName: member1-sa
      containers:
        - name: member1
          image: rockylinux:8.8
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 2048m
              memory: 1024Mi
            limits:
              cpu: 2048m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data
            - name: hostpath-volume
              mountPath: /rocky
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - "sleep 100000"

      volumes:
        - name: data
          emptyDir:
            sizeLimit: "5Gi"
        - name: hostpath-volume
          hostPath:
            path: /Users/a06837/Downloads/SW/Temp/rocky
