apiVersion: v1
kind: Service
metadata:
  name: quorum-validator3-1
  labels:
    app: validator3
  namespace: quorum
spec:
  type: NodePort
  selector:
    app: validator3
  ports:
    - port: 8545
      targetPort: 8545
      nodePort: 30075
      protocol: TCP
      name: validator3rpc