---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: block-explorer
          image: chainz-explorer:1.0.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_NODE_URL
              value: "http://3.37.46.84:31070"
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
